import '../styles/globals.css'
import { Nunito } from '@next/font/google'

const nunito = Nunito({ 
  subsets: ['latin'],
  variable:'--font-nunito',
 })

export const metadata = {
  
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} h-[100%] flex`}>{children}</body>
    </html>
  )
}
